# Generated by Django 5.2.10 on 2026-01-16 01:22

import commons.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='account_set', to='auth.group', verbose_name='グループ')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_set', to='auth.permission', verbose_name='ユーザー権限')),
            ],
            options={
                'verbose_name': 'アカウント',
                'verbose_name_plural': 'アカウント',
                'db_table': 'account',
            },
            managers=[
                ('objects', commons.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50, verbose_name='アカウント種類')),
            ],
            options={
                'verbose_name': 'アカウント種類マスタ',
                'verbose_name_plural': 'アカウント種類マスタ',
                'db_table': 'account_type',
            },
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=100, verbose_name='年代')),
            ],
            options={
                'verbose_name': '年代マスタ',
                'verbose_name_plural': '年代マスタ',
                'db_table': 'age_group',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '申請ステータスマスタ',
                'verbose_name_plural': '申請ステータスマスタ',
                'db_table': 'application_statuses',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='エリア名')),
            ],
            options={
                'verbose_name': 'エリア',
                'verbose_name_plural': 'エリア',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='性別')),
            ],
            options={
                'verbose_name': '性別マスタ',
                'verbose_name_plural': '性別マスタ',
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='ImageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='画像ステータス')),
            ],
            options={
                'verbose_name': '画像ステータスマスタ',
                'verbose_name_plural': '画像ステータスマスタ',
                'db_table': 'image_statuses',
            },
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='予約ステータス')),
            ],
            options={
                'verbose_name': '予約ステータスマスタ',
                'verbose_name_plural': '予約ステータスマスタ',
                'db_table': 'reservation_statuses',
            },
        ),
        migrations.CreateModel(
            name='Reservator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('full_name_kana', models.CharField(max_length=100, verbose_name='氏名かな')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '予約者情報',
                'verbose_name_plural': '予約者情報',
                'db_table': 'reservators',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='点数')),
                ('review_text', models.TextField(verbose_name='レビュー')),
                ('like_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
            options={
                'verbose_name': '口コミ',
                'verbose_name_plural': '口コミ',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(max_length=100, verbose_name='シーン名')),
            ],
            options={
                'verbose_name': '利用シーン',
                'verbose_name_plural': '利用シーン',
                'db_table': 'scene',
            },
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='企業名')),
            ],
            options={
                'verbose_name': '企業アカウント情報',
                'verbose_name_plural': '企業アカウント情報',
                'db_table': 'company_account',
            },
            bases=('commons.account',),
            managers=[
                ('objects', commons.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=255, verbose_name='ニックネーム')),
                ('sub_email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('location', models.CharField(max_length=255, verbose_name='現在位置')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('review_count', models.IntegerField(default=0, verbose_name='口コミ数')),
                ('total_likes', models.IntegerField(default=0, verbose_name='総いいね数')),
                ('standard_score', models.IntegerField(default=0, verbose_name='標準点')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.agegroup', verbose_name='年代')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.gender', verbose_name='性別')),
            ],
            options={
                'verbose_name': '顧客アカウント情報',
                'verbose_name_plural': '顧客アカウント情報',
                'db_table': 'customer_account',
            },
            bases=('commons.account',),
            managers=[
                ('objects', commons.models.AccountManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.accounttype', verbose_name='種類'),
        ),
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('reset_token', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='リセットトークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_flag', models.BooleanField(default=False, verbose_name='使用済みフラグ')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='リセット要求日時')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アカウント')),
            ],
            options={
                'verbose_name': 'パスワードリセットログ',
                'verbose_name_plural': 'パスワードリセットログ',
                'db_table': 'password_reset_log',
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, verbose_name='画像パス')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='commons.review', verbose_name='口コミ')),
            ],
            options={
                'verbose_name': '口コミ写真',
                'verbose_name_plural': '口コミ写真',
                'db_table': 'review_photos',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(verbose_name='通報内容')),
                ('report_status', models.BooleanField(verbose_name='通報ステータス')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='通報者')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.review', verbose_name='口コミ')),
            ],
            options={
                'verbose_name': '通報された口コミ',
                'verbose_name_plural': '通報された口コミ',
                'db_table': 'review_reports',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('map_location', models.CharField(max_length=255, verbose_name='地図')),
                ('business_hours', models.CharField(max_length=50, verbose_name='営業時間')),
                ('seats', models.IntegerField(verbose_name='席数')),
                ('budget', models.IntegerField(verbose_name='予算')),
                ('reservable', models.BooleanField(default=True, verbose_name='予約可否')),
                ('editable', models.BooleanField(default=True, verbose_name='編集可能')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.area', verbose_name='エリア')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.scene', verbose_name='利用シーン')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='commons.customeraccount', verbose_name='作成者')),
            ],
            options={
                'verbose_name': '店舗基本情報',
                'verbose_name_plural': '店舗基本情報',
                'db_table': 'stores',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.store', verbose_name='店舗'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='来店日')),
                ('visit_time', models.TimeField(verbose_name='来店時刻')),
                ('visit_count', models.IntegerField(verbose_name='来店人数')),
                ('course', models.CharField(max_length=255, verbose_name='コース')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='キャンセル理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.reservationstatus', verbose_name='予約ステータス')),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.reservator', verbose_name='予約者')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='StoreAccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(max_length=255, verbose_name='添付資料')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('branch_name', models.CharField(max_length=100, verbose_name='支店名')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申込者名')),
                ('relation_to_store', models.CharField(max_length=50, verbose_name='店舗との関係')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.applicationstatus', verbose_name='申請ステータス')),
                ('target_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='対象店舗')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.customeraccount', verbose_name='申請者')),
            ],
            options={
                'verbose_name': '店舗アカウント申請',
                'verbose_name_plural': '店舗アカウント申請',
                'db_table': 'store_account_requests',
            },
        ),
        migrations.CreateModel(
            name='StoreAccountRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.storeaccountrequest', verbose_name='申請')),
                ('request_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.applicationstatus', verbose_name='申請ステータス')),
            ],
            options={
                'verbose_name': '店舗アカウント申請ログ',
                'verbose_name_plural': '店舗アカウント申請ログ',
                'db_table': 'store_account_request_logs',
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, verbose_name='画像パス')),
                ('image_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.imagestatus', verbose_name='画像ステータス')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '店舗画像',
                'verbose_name_plural': '店舗画像',
                'db_table': 'store_images',
            },
        ),
        migrations.CreateModel(
            name='StoreMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, verbose_name='メニュー名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image_path', models.CharField(max_length=255, verbose_name='メニュー画像パス')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'メニュー',
                'verbose_name_plural': 'メニュー',
                'db_table': 'store_menus',
            },
        ),
        migrations.CreateModel(
            name='StoreOnlineReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.BooleanField(verbose_name='予約受付状況')),
                ('available_seats', models.IntegerField(verbose_name='予約可能席数')),
                ('date', models.DateField(verbose_name='日付')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '店舗ネット予約情報',
                'verbose_name_plural': '店舗ネット予約情報',
                'db_table': 'store_online_reservations',
            },
        ),
        migrations.CreateModel(
            name='TempRequestMailLog',
            fields=[
                ('temp_request_token', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='仮申請メールトークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_flag', models.BooleanField(default=False, verbose_name='使用済みフラグ')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='要求日時')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.customeraccount', verbose_name='申請者')),
            ],
            options={
                'verbose_name': '仮申請メールログ',
                'verbose_name_plural': '仮申請メールログ',
                'db_table': 'temp_request_mail_log',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.customeraccount', verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='reservator',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.customeraccount', verbose_name='顧客アカウント'),
        ),
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_email', models.EmailField(max_length=255, verbose_name='管理者メールアドレス')),
                ('permission_flag', models.BooleanField(default=False, verbose_name='権限フラグ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.store', verbose_name='店舗情報')),
            ],
            options={
                'verbose_name': '店舗アカウント情報',
                'verbose_name_plural': '店舗アカウント情報',
                'db_table': 'store_account',
            },
            bases=('commons.account',),
            managers=[
                ('objects', commons.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='ブロック済み')),
                ('is_muted', models.BooleanField(default=False, verbose_name='ミュート済み')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='フォロー日時')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followee', to='commons.customeraccount', verbose_name='フォロー先')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower', to='commons.customeraccount', verbose_name='フォロー元')),
            ],
            options={
                'verbose_name': 'フォロー',
                'verbose_name_plural': 'フォロー',
                'db_table': 'follows',
                'unique_together': {('follower', 'followee')},
            },
        ),
    ]
