# Generated by Django 5.2.10 on 2026-01-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_store_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='アカウント種類'),
        ),
    ]
