# Generated by Django 5.2.10 on 2026-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_alter_accounttype_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewphoto',
            name='image_path',
            field=models.ImageField(upload_to='review/photos/', verbose_name='画像'),
        ),
    ]
