# Generated by Django 5.2.10 on 2026-01-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_alter_reviewphoto_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/cover/', verbose_name='カバー画像'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/icon/', verbose_name='アイコン画像'),
        ),
    ]
