# Generated by Django 5.2.10 on 2026-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_alter_account_groups_alter_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='inquiry_log',
            field=models.TextField(blank=True, default='', verbose_name='問い合わせ内容'),
        ),
    ]
