# Generated by Django 4.0 on 2026-01-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commons', '0007_customeraccount_inquiry_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='来店終了時刻'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='来店開始時刻'),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_1',
            field=models.TimeField(blank=True, null=True, verbose_name='閉店時間①'),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_2',
            field=models.TimeField(blank=True, null=True, verbose_name='閉店時間②'),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_1',
            field=models.TimeField(blank=True, null=True, verbose_name='開店時間①'),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_2',
            field=models.TimeField(blank=True, null=True, verbose_name='開店時間②'),
        ),
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='storeonlinereservation',
            name='available_seats',
            field=models.IntegerField(default=0, verbose_name='予約可能席数'),
        ),
        migrations.AlterField(
            model_name='storeonlinereservation',
            name='booking_status',
            field=models.BooleanField(default=True, verbose_name='予約受付状況'),
        ),
        migrations.AlterField(
            model_name='storeonlinereservation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗'),
        ),
        migrations.AddConstraint(
            model_name='storeonlinereservation',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='uniq_store_date'),
        ),
    ]
