# Generated by Django 5.2.10 on 2026-01-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_customeraccount_inquiry_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='報告内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='報告日時')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.customeraccount', verbose_name='報告者')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.store', verbose_name='対象店舗')),
            ],
            options={
                'verbose_name': '店舗情報の報告',
                'verbose_name_plural': '店舗情報の報告',
                'db_table': 'store_info_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInfoReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_reports/photos/', verbose_name='写真')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='commons.storeinforeport', verbose_name='報告')),
            ],
            options={
                'verbose_name': '店舗情報報告の写真',
                'verbose_name_plural': '店舗情報報告の写真',
                'db_table': 'store_info_report_photos',
            },
        ),
    ]
