# Generated by Django 4.0 on 2026-01-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0009_storeinforeport_storeinforeportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='genre',
            field=models.CharField(default=1, max_length=100, verbose_name='ジャンル'),
            preserve_default=False,
        ),
    ]
