# Generated by Django 4.0 on 2026-01-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0010_store_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='store/images/', verbose_name='画像ファイル（新）'),
        ),
        migrations.AddField(
            model_name='storemenu',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='store/menus/', verbose_name='メニュー画像ファイル（新）'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='画像パス（旧）'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commons.store', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='メニュー画像パス（旧）'),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='commons.store', verbose_name='店舗'),
        ),
    ]
