# Generated by Django 5.2.10 on 2026-01-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0011_storeimage_image_file_storemenu_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='cover_image',
            field=models.ImageField(blank=True, default='customer/cover/default_cover.jpg', null=True, upload_to='customer/cover/', verbose_name='カバー画像'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='icon_image',
            field=models.ImageField(blank=True, default='customer/icon/default_cover.jpg', null=True, upload_to='customer/icon/', verbose_name='アイコン画像'),
        ),
    ]
