# Generated by Django 5.2.10 on 2026-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0012_alter_customeraccount_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
