# Generated by Django 4.0 on 2026-01-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0013_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='アクセス日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='commons.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '店舗アクセスログ',
                'verbose_name_plural': '店舗アクセスログ',
                'db_table': 'store_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
