# Generated by Django 4.0 on 2026-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0014_storeaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='camera',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='使っているカメラ'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='first_name_kana',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='めい'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='genre_focus',
            field=models.TextField(blank=True, default='', verbose_name='得意ジャンル・こだわり'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='introduction',
            field=models.TextField(blank=True, default='', verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='last_name_kana',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='せい'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='職業'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='サブタイトル'),
        ),
    ]
