# Generated by Django 4.0 on 2026-01-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0015_customeraccount_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='trust_score',
            field=models.FloatField(default=50.0, verbose_name='信頼度スコア'),
        ),
    ]
