# Generated by Django 4.0 on 2026-01-29 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0015_customeraccount_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
    ]
