# Generated by Django 5.2.10 on 2026-01-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0016_customeraccount_trust_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='scene_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='シーン名'),
        ),
    ]
