# Generated by Django 4.0 on 2026-01-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0016_customeraccount_trust_score'),
        ('commons', '0016_review_liked_users'),
    ]

    operations = [
    ]
