# Generated by Django 4.0 on 2026-01-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0017_merge_20260129_1139'),
        ('commons', '0017_merge_20260129_1140'),
    ]

    operations = [
    ]
