# Generated by Django 4.0 on 2026-01-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0018_genre_review_liked_users_store_genre_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='genre_master',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
