# Generated by Django 4.0 on 2026-01-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0019_remove_customeraccount_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeaccountrequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='storeaccountrequest',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_account_requests/licenses/', verbose_name='営業許可証'),
        ),
    ]
