# Generated by Django 4.0 on 2026-02-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0020_remove_storeaccountrequest_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaccountrequest',
            name='admin_email',
            field=models.EmailField(default='', max_length=255, verbose_name='管理者メールアドレス'),
        ),
    ]
