# Generated by Django 4.0 on 2026-02-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0022_genre_store_genre_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='storeaccount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='店舗情報'),
        ),
        migrations.AlterField(
            model_name='storeinforeport',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.store', verbose_name='対象店舗'),
        ),
    ]
