# Generated by Django 4.0 on 2026-02-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0023_alter_review_store_alter_storeaccount_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='map_location',
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
