# Generated by Django 4.0 on 2026-02-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0024_remove_store_map_location_store_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_icon',
            field=models.ImageField(blank=True, null=True, upload_to='store/icons/', verbose_name='店舗アイコン'),
        ),
    ]
