# Generated by Django 4.0 on 2026-02-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0025_store_store_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_icon',
        ),
        migrations.AddField(
            model_name='storeimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.account', verbose_name='投稿者'),
        ),
    ]
