# Generated by Django 4.0 on 2026-02-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0027_alter_storeimage_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='follower_count',
            field=models.IntegerField(default=0, verbose_name='フォロワー数'),
        ),
    ]
